apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snowflake-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowflake-id-generator
  template:
    metadata:
      labels:
        app: snowflake-id-generator
    spec:
      initContainers:
        - name: init-worker-id
          image: alpine:latest
          command: ["sh", "-c"]
          args:
            - |
              POD_HASH=$(echo "$HOSTNAME" | cksum | awk '{print $1}')
              WORKER_ID=$(( (POD_HASH % 31) + 1 ))
              echo "$WORKER_ID" > /shared-data/worker-id.txt
          volumeMounts:
            - mountPath: /shared-data
              name: shared-data
      containers:
        - image: snowflake-id-generator:1.0.0
          name: snowflake-id-generator
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  key: SPRING_APPLICATION_NAME
                  name: app-config
            - name: SNOWFLAKE-SETTINGS_STARTING-EPOCH
              valueFrom:
                configMapKeyRef:
                  key: SNOWFLAKE-SETTINGS_STARTING-EPOCH
                  name: app-config
            - name: SNOWFLAKE-SETTINGS_DATACENTER-ID
              valueFrom:
                configMapKeyRef:
                  key: SNOWFLAKE-SETTINGS_DATACENTER-ID
                  name: app-config
          command: [ "sh", "-c" ]
          args:
            - |
              _ID=$(cat /shared-data/worker-id.txt)
              exec java -jar app.jar --snowflake-settings.worked-id="$_ID"
          volumeMounts:
            - name: app-config-volume
              mountPath: /config
              readOnly: true
            - name: shared-data
              mountPath: /shared-data
              readOnly: true
          livenessProbe:
            httpGet:
              path: /management/health/livenessState
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readinessState
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      volumes:
        - name: app-config-volume
          configMap:
            name: app-config
        - name: shared-data
          emptyDir: {}
